version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: docker login -u $DOCKER_LOGIN_ID -p $DOCKER_LOGIN_PASSWORD

     - run: docker build -t retzero/gbs_ubuntu16.04 .

     - run: docker push retzero/gbs_ubuntu16.04
